<?php

/**
 * @package     TLWeb.Plugin
 * @subpackage  Fields.Prettyprotecteddownloads
 *
 * @copyright   Copyright (C) 2026 TLWebdesign. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

namespace TLWeb\Plugin\Fields\Prettyprotecteddownloads\Helper;

// phpcs:disable PSR1.Files.SideEffects
\defined('_JEXEC') or die;
// phpcs:enable PSR1.Files.SideEffects

/**
 * The stored value of a Pretty Protected Downloads field, and the rules for the files it names.
 *
 * A field value is a JSON list of entries, one per file:
 *
 *   {"uuid": "...", "filename": "report-<uuid>.pdf", "original": "Report 2026.pdf",
 *    "button": "...", "title": "...", "description": "...", "icon": "...", "class": "..."}
 *
 * `filename` is the name on disk and always ends in the entry's own uuid, so an entry
 * can only ever point at the file that was uploaded for it. `original` is the name the
 * editor uploaded, used as the name of the download.
 *
 * Nothing in here touches Joomla, the database or the disk, so it is what the tests
 * cover most closely.
 */
final class Entries
{
    /**
     * A name as it is stored on disk: no directory, one extension.
     */
    public const STORED_NAME = '/^[a-z0-9_\-]+\.[a-z0-9]+$/i';

    /**
     * An RFC 4122 uuid, as generated by uuid().
     */
    public const UUID = '/^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i';

    /**
     * A name this plugin wrote: a stored name that ends in a uuid. Nothing is ever
     * read, listed or deleted from the storage folder that does not match this, so a
     * folder shared with anything else -- or a badly chosen one -- comes to no harm.
     */
    public const OWN_FILE = '/^[a-z0-9_\-]+-[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}\.[a-z0-9]+$/i';

    /**
     * The text keys an entry carries besides the uuid and filenames.
     */
    private const TEXT_KEYS = ['button', 'title', 'description', 'icon', 'class'];

    /**
     * Decode a stored value, or one posted by the form, into a list of entry arrays.
     *
     * @param   mixed  $value  A JSON string, an already decoded array, or anything else.
     *
     * @return  array[]
     */
    public static function decode(mixed $value): array
    {
        if (\is_string($value) && $value !== '') {
            $value = json_decode($value, true);
        }

        if (!\is_array($value)) {
            return [];
        }

        return array_values(array_filter($value, 'is_array'));
    }

    /**
     * Clean one entry as it comes out of the form, or null when it names no stored file.
     *
     * @param   array  $row  The raw subform row.
     *
     * @return  ?array
     */
    public static function normalise(array $row): ?array
    {
        $entry = [
            'uuid'     => trim((string) ($row['uuid'] ?? '')),
            'filename' => trim((string) ($row['filename'] ?? '')),
            'original' => self::cleanOriginal((string) ($row['original'] ?? '')),
        ];

        if (!self::belongsTogether($entry['uuid'], $entry['filename'])) {
            return null;
        }

        foreach (self::TEXT_KEYS as $key) {
            $entry[$key] = trim((string) ($row[$key] ?? ''));
        }

        return $entry;
    }

    /**
     * Whether a stored filename is the one generated for this uuid.
     *
     * @param   string  $uuid      The entry uuid.
     * @param   string  $filename  The stored filename.
     *
     * @return  bool
     */
    public static function belongsTogether(string $uuid, string $filename): bool
    {
        return preg_match(self::UUID, $uuid) === 1
            && preg_match(self::STORED_NAME, $filename) === 1
            && preg_match('/-' . preg_quote($uuid, '/') . '\.[a-z0-9]+$/i', $filename) === 1;
    }

    /**
     * The stored filenames that were in the old entries and are gone from the new ones.
     *
     * Entries are matched on uuid, so a file whose title or button text changed is kept.
     *
     * @param   array[]  $old  Entries before the save.
     * @param   array[]  $new  Entries after the save.
     *
     * @return  string[]
     */
    public static function removedFilenames(array $old, array $new): array
    {
        $kept = [];

        foreach ($new as $entry) {
            if (!empty($entry['uuid'])) {
                $kept[(string) $entry['uuid']] = true;
            }
        }

        $removed = [];

        foreach ($old as $entry) {
            $uuid     = (string) ($entry['uuid'] ?? '');
            $filename = (string) ($entry['filename'] ?? '');

            if ($uuid !== '' && $filename !== '' && !isset($kept[$uuid])) {
                $removed[] = $filename;
            }
        }

        return array_values(array_unique($removed));
    }

    /**
     * Gather the entries a child field holds across all rows of a subform value.
     *
     * @param   mixed   $subformValue  The subform value, JSON or decoded.
     * @param   string  $fieldKey      The child's key in each row, "field{id}".
     *
     * @return  array[]
     */
    public static function fromSubform(mixed $subformValue, string $fieldKey): array
    {
        $entries = [];

        foreach (self::decode($subformValue) as $row) {
            if (!empty($row[$fieldKey])) {
                array_push($entries, ...self::decode($row[$fieldKey]));
            }
        }

        return $entries;
    }

    /**
     * The ids of the Pretty Protected Downloads fields a subform field is built from.
     *
     * @param   mixed  $fieldparams      The subform field's fieldparams, JSON or decoded.
     * @param   array  $downloadFieldIds The ids of all Pretty Protected Downloads fields, as keys.
     *
     * @return  int[]
     */
    public static function subformChildIds(mixed $fieldparams, array $downloadFieldIds): array
    {
        if (\is_string($fieldparams)) {
            $fieldparams = json_decode($fieldparams, true);
        }

        if (!\is_array($fieldparams) || !\is_array($fieldparams['options'] ?? null)) {
            return [];
        }

        $ids = [];

        foreach ($fieldparams['options'] as $option) {
            $id = (int) ($option['customfield'] ?? 0);

            if ($id > 0 && isset($downloadFieldIds[$id])) {
                $ids[$id] = $id;
            }
        }

        return array_values($ids);
    }

    /**
     * Every stored filename mentioned anywhere in a field value.
     *
     * Walks the value without knowing its shape, so a direct field, a subform row and a
     * subform whose child value was saved as a JSON string all give up their files.
     *
     * @param   mixed  $value  A field value, JSON or decoded.
     *
     * @return  string[]
     */
    public static function filenamesIn(mixed $value): array
    {
        if (\is_string($value)) {
            $trimmed = ltrim($value);

            if ($trimmed === '' || ($trimmed[0] !== '[' && $trimmed[0] !== '{')) {
                return [];
            }

            $value = json_decode($value, true);
        }

        if (!\is_array($value)) {
            return [];
        }

        $found = [];

        foreach ($value as $key => $child) {
            if ($key === 'filename' && \is_string($child) && preg_match(self::OWN_FILE, $child)) {
                $found[] = $child;
            } elseif (\is_array($child) || \is_string($child)) {
                array_push($found, ...self::filenamesIn($child));
            }
        }

        return $found;
    }

    /**
     * The name to store an upload under.
     *
     * @param   string  $original  The name the file was uploaded with.
     * @param   string  $uuid      The entry uuid.
     *
     * @return  ?string  Null when the upload has no usable extension.
     */
    public static function storedName(string $original, string $uuid): ?string
    {
        $extension = self::extension($original);

        if ($extension === '' || !preg_match('/^[a-z0-9]+$/', $extension)) {
            return null;
        }

        $base = pathinfo($original, PATHINFO_FILENAME);
        $base = strtolower(trim((string) preg_replace('/[^a-z0-9_-]+/i', '-', $base), '-'));
        $base = substr($base, 0, 80) ?: 'file';

        return $base . '-' . $uuid . '.' . $extension;
    }

    /**
     * The name a visitor's browser saves the download as.
     *
     * The uploaded name when the entry has one, otherwise the stored name without the
     * uuid it was given on upload. Either way it ends in the stored file's own
     * extension: the uploaded name is an editor's text, and a PDF that saves as
     * "report.html" would be opened as a web page.
     *
     * @param   array  $entry  The entry.
     *
     * @return  string
     */
    public static function downloadName(array $entry): string
    {
        $filename  = (string) ($entry['filename'] ?? '');
        $uuid      = (string) ($entry['uuid'] ?? '');
        $extension = self::extension($filename);
        $original  = self::cleanOriginal((string) ($entry['original'] ?? ''));

        if ($original !== '') {
            return self::extension($original) === $extension ? $original : $original . '.' . $extension;
        }

        if ($uuid !== '') {
            $filename = str_replace('-' . $uuid . '.', '.', $filename);
        }

        return $filename;
    }

    /**
     * The lower-case extension of a filename, without the dot.
     *
     * @param   string  $filename  The filename.
     *
     * @return  string
     */
    public static function extension(string $filename): string
    {
        return strtolower(pathinfo($filename, PATHINFO_EXTENSION));
    }

    /**
     * A new version 4 uuid.
     *
     * @return  string
     */
    public static function uuid(): string
    {
        $data    = random_bytes(16);
        $data[6] = \chr((\ord($data[6]) & 0x0f) | 0x40);
        $data[8] = \chr((\ord($data[8]) & 0x3f) | 0x80);

        return vsprintf('%s%s-%s-%s-%s-%s%s%s', str_split(bin2hex($data), 4));
    }

    /**
     * An uploaded name made safe to show and to send in a header: no directory, no
     * control characters, no quotes, and not absurdly long.
     *
     * @param   string  $name  The name.
     *
     * @return  string
     */
    private static function cleanOriginal(string $name): string
    {
        $name = basename(str_replace('\\', '/', $name));
        $name = (string) preg_replace('/[\x00-\x1F\x7F"]+/u', '', $name);
        $name = trim($name, " .\t");

        if (mb_strlen($name) > 150) {
            $extension = self::extension($name);
            $name      = mb_substr($name, 0, 140) . ($extension !== '' ? '.' . $extension : '');
        }

        return $name;
    }
}
